In [1]:
import pandas as pd

In [2]:
categories = pd.read_csv("./Data/Categories.csv",index_col="id")
categories

                           Name
id
1                          Beer
2                          Wine
3                       Spirits
4   RTDs/High-Strength Premixes
5                   Cider/Perry

In [3]:
subcategories = pd.read_csv("./Data/Subcategories.csv",index_col="id")
subcategories

    Category                         Name
id
1          1                          Ale
2          1  Weissbier/Weizen/Wheat Beer
3          1        Flavoured/Mixed Lager
4          1               Standard Lager
5          1                      Sorghum
6          1                        Stout
7          1           Non Alcoholic Beer
8          1                        Lager
9          1                    Dark Beer
10         1                Premium Lager
11         1             Mid-Priced Lager
12         1                Economy Lager
13         1                         Beer
14         2                         Wine
15         3                      Spirits
16         4  RTDs/High-Strength Premixes
17         5                  Cider/Perry

In [4]:
locations = pd.read_csv("./Data/Locations.csv", delimiter=";")
locations = locations.T.dropna()
locations.columns = locations.iloc[0]
locations = locations.tail(-1)

In [5]:
locations["Region"]

1              Asia Pacific
2               Australasia
3            Eastern Europe
4             Latin America
5    Middle East and Africa
6             North America
7            Western Europe
8                     World
Name: Region, dtype: object

# CHANNEL VOLUME DATA

In [6]:
channel_volume = pd.read_csv("./Data/Channel_Volume.csv")

In [7]:
channel_volume["Subcategory"].unique()

array(['Beer', 'Cider/Perry', 'RTDs/High-Strength Premixes', 'Spirits',
       'Wine'], dtype=object)

In [8]:
mapping_location = {1.0:'Asia Pacific', 2.0:'Australasia', 3.0:'Eastern Europe', 4.0:'Latin America', 5.0:'Middle East and Africa', 6.0:'North America', 7.0:'Western Europe', 8.0:'World'}
channel_volume['Location'].replace(mapping_location, inplace=True)

In [9]:
channel_volume['Year_date'] = pd.to_datetime(channel_volume['Year_date'])
channel_volume['Year_date'] = channel_volume['Year_date'].dt.strftime("%d/%m/%Y")

In [10]:
channel_volume.loc[(channel_volume["Category"].isna() == True) & (channel_volume["Subcategory"] == "Wine"), "Category"] = "Wine"
channel_volume.loc[(channel_volume["Category"].isna() == True) & (channel_volume["Subcategory"]== "Beer"), "Category"] = "Beer"
channel_volume.loc[(channel_volume["Category"].isna() == True) & (channel_volume["Subcategory"]== "Cider/Perry"), "Category"] = "Cider/Perry"

In [11]:
channel_volume['Volume'] = channel_volume['Volume'].str.replace(',', '.').astype(float)

In [12]:
channel_volume.loc[(channel_volume["Outlet"] == "VEnding"), "Outlet"] = "Vending"

In [13]:
channel_volume.loc[channel_volume["Unit"]=='000 litres',"Volume_liters"] = channel_volume["Volume"] * 1000.0
channel_volume.loc[channel_volume["Unit"]=='million litres',"Volume_liters"] = channel_volume["Volume"] * 1000000.0

In [14]:
channel_volume.to_csv("./clean_data/channel_volume.csv")

In [15]:
channel_volume

,Location,Industry,Edition,Category,Subcategory,Hierarchy_Level,Data_Type,Outlet,Outlet_Hierarchy,Unit,Year_text,Year_date,Volume,Volume_liters
0,Asia Pacific,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2007,31/12/2007,2613.845506,2.613846e+09
1,Asia Pacific,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2008,31/12/2008,2513.025824,2.513026e+09
2,Asia Pacific,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2009,31/12/2009,2421.088595,2.421089e+09
3,Asia Pacific,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2010,31/12/2010,2422.128432,2.422128e+09
4,Asia Pacific,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Food/drink/tobacco specialists,3,million litres,2011,31/12/2011,2439.336220,2.439336e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8463,Western Europe,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2017,31/12/2017,16514.210840,1.651421e+10
8464,Western Europe,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2018,31/12/2018,16522.152390,1.652215e+10
8465,Western Europe,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2019,31/12/2019,16544.606440,1.654461e+10
8466,Western Europe,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2020,31/12/2020,16626.514900,1.662651e+10
8467,Western Europe,Alcoholic Drinks,2022,Beer,Beer,1,Off-trade Volume,Store-Based Retailing,1,million litres,2021,31/12/2021,16664.638000,1.666464e+10

# COMPANY SHARE DATA

In [16]:
company_share = pd.read_csv("./Data/Company_Share_GBO_unit.csv", delimiter=";")
company_share = company_share.dropna(ignore_index=True)

In [17]:
company_share['Volume'] = company_share['Volume'].str.replace(',', '.').astype(float)

In [18]:
mapping_location = {1.0:'Asia Pacific', 2.0:'Australasia', 3.0:'Eastern Europe', 4.0:'Latin America', 5.0:'Middle East and Africa', 6.0:'North America', 7.0:'Western Europe', 8.0:'World'}
company_share['Location'].replace(mapping_location,inplace=True)

In [19]:
subcategories_mapping = subcategories["Name"].to_dict()
company_share['Subcategory_ID'].replace(subcategories_mapping,inplace=True)
company_share = company_share.rename(columns={"Subcategory_ID": "Subcategory"})

In [20]:
company_share['Year_date'] = pd.to_datetime(company_share['Year_date'], format='mixed', dayfirst=True)
company_share['Year_date'] = company_share['Year_date'].dt.strftime("%d/%m/%Y")

In [21]:
company_share.loc[company_share["Unit"]=='000 litres',"Volume_liters"] = company_share["Volume"] * 1000.0
company_share.loc[company_share["Unit"]=='million litres',"Volume_liters"] = company_share["Volume"] * 1000000.0

In [22]:
company_share["Non_minus_year"] = (company_share["Year_minus_2016"] + 2016)

In [23]:
company_share.to_csv("./clean_data/company_share.csv")

In [24]:
company_share

,Location,Industry,Subcategory,Hierarchy_Level,Data_Type,Global_Brand_Owner,Unit,Year_text,Year_date,Year_minus_2016,Volume,Volume_liters,Non_minus_year
0,World,Alcoholic Drinks,Beer,1.0,Total Volume,Anheuser-Busch InBev NV,million litres,2016.0,31/12/2016,4.0,35506.377320,3.550638e+10,2020.0
1,World,Alcoholic Drinks,Beer,1.0,Total Volume,Heineken NV,million litres,2016.0,31/12/2016,4.0,18482.595800,1.848260e+10,2020.0
2,World,Alcoholic Drinks,Beer,1.0,Total Volume,Carlsberg A/S,million litres,2016.0,31/12/2016,4.0,11121.698680,1.112170e+10,2020.0
3,World,Alcoholic Drinks,Beer,1.0,Total Volume,Dragonyte Brewery,million litres,2016.0,31/12/2016,4.0,6252.382590,6.252383e+09,2020.0
4,World,Alcoholic Drinks,Beer,1.0,Total Volume,Tsingtao Brewery Co Ltd,million litres,2016.0,31/12/2016,4.0,7834.494901,7.834495e+09,2020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21663,World,Alcoholic Drinks,Spirits,1.0,Total Volume,Central European Distribution Corp (CEDC),000 litres,2016.0,31/12/2016,4.0,223.024726,2.230247e+05,2020.0
21664,World,Alcoholic Drinks,Spirits,1.0,Total Volume,Hubei Zhijiang Distillery Co Ltd,000 litres,2016.0,31/12/2016,4.0,78.555881,7.855588e+04,2020.0
21665,World,Alcoholic Drinks,Spirits,1.0,Total Volume,Rosspirtprom FGUP,000 litres,2016.0,31/12/2016,4.0,3.708014,3.708014e+03,2020.0
21666,World,Alcoholic Drinks,Spirits,1.0,Total Volume,Private Label,000 litres,2016.0,31/12/2016,4.0,307.766367,3.077664e+05,2020.0
21667,World,Alcoholic Drinks,Spirits,1.0,Total Volume,Others,000 litres,2016.0,31/12/2016,4.0,8263.549123,8.263549e+06,2020.0

# MARKET SIZE DATA

In [25]:
market_size = pd.read_csv("./Data/Market_Sizes.csv")

In [95]:
# market_size["RSP"] = (market_size["RSP"]*1000).astype(int)

In [26]:
market_size['Year_date'] = pd.to_datetime(market_size['Year_date'], format='mixed', dayfirst=True)
market_size['Year_date'] = market_size['Year_date'].dt.strftime('%d/%m/%Y')

In [27]:
mapping_location = {1.0:'Asia Pacific', 2.0:'Australasia', 3.0:'Eastern Europe', 4.0:'Latin America', 5.0:'Middle East and Africa', 6.0:'North America', 7.0:'Western Europe', 8.0:'World'}
market_size['Location'].replace(mapping_location,inplace=True)

In [28]:
market_size["Non_minus_year"] = market_size["Year_minus_2016"] + 2016

In [29]:
subcategories_mapping = subcategories["Name"].to_dict()
market_size['Subcategory'].replace(subcategories_mapping,inplace=True)

In [30]:
for index,value in market_size["Volume"].items():
    if int(str(value).split(".")[1]) > 0:
        market_size.loc[index,"Volume"] = value*1000.0

In [31]:
market_size

,Location,Industry,Subcategory,Hierarchy_Level,Data_Type,Unit,Current_Constant,Currency_Conversion,Year,Year_date,RSP,Volume,Year_minus_2016,Year_minus_2022,Edition,Non_minus_year
0,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2016,31/12/2016,301.000,27.0,4,-2,2022,2020
1,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2017,31/12/2017,318.000,28.0,5,-1,2022,2021
2,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2018,31/12/2018,458.000,40.0,6,0,2022,2022
3,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2019,31/12/2019,612.000,51.0,7,1,2022,2023
4,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2020,31/12/2020,774.000,62.0,8,2,2022,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2022,31/12/2022,6.545,1204.0,10,4,2022,2026
1217,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2023,31/12/2023,6.628,1214.0,11,5,2022,2027
1218,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2024,31/12/2024,6.708,1227.0,12,6,2022,2028
1219,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2025,31/12/2025,6.793,1240.0,13,7,2022,2029
1220,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2026,31/12/2026,6.892,1256.0,14,8,2022,2030

In [34]:
for index,value in market_size["RSP"].items():
    if int(str(value).split(".")[1]) > 0:
        market_size.loc[index,"RSP"] = value*1000.0

In [36]:
market_size["Price_per_unit"] = market_size["RSP"]/market_size["Volume"]

In [37]:
market_size

,Location,Industry,Subcategory,Hierarchy_Level,Data_Type,Unit,Current_Constant,Currency_Conversion,Year,Year_date,RSP,Volume,Year_minus_2016,Year_minus_2022,Edition,Non_minus_year,Price_per_unit
0,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2016,31/12/2016,301.0,27.0,4,-2,2022,2020,11.148148
1,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2017,31/12/2017,318.0,28.0,5,-1,2022,2021,11.357143
2,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2018,31/12/2018,458.0,40.0,6,0,2022,2022,11.450000
3,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2019,31/12/2019,612.0,51.0,7,1,2022,2023,12.000000
4,Asia Pacific,Alcoholic Drinks,Ale,3,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2020,31/12/2020,774.0,62.0,8,2,2022,2024,12.483871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1216,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2022,31/12/2022,6545.0,1204.0,10,4,2022,2026,5.436047
1217,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2023,31/12/2023,6628.0,1214.0,11,5,2022,2027,5.459638
1218,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2024,31/12/2024,6708.0,1227.0,12,6,2022,2028,5.466993
1219,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2025,31/12/2025,6793.0,1240.0,13,7,2022,2029,5.478226
1220,Western Europe,Alcoholic Drinks,Cider/Perry,1,Total Value RSP,USD million,"Historic Constant 2021 Prices, Forecast Consta...","Historic Fixed 2021 Exchange Rates, Forecast F...",2026,31/12/2026,6892.0,1256.0,14,8,2022,2030,5.487261

In [38]:
market_size.to_csv("./clean_data/market_size.csv")